M48
; DRILL file {KiCad 9.0.6} date 2026-02-06T12:48:51+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-06T12:48:51+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.450
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C5.500
%
G90
G05
T1
X96.775Y-81.35
X96.775Y-85.75
T2
X110.0Y-47.5
T3
X118.0Y-63.0
X173.25Y-48.0
T4
X95.48Y-142.0
X95.75Y-49.25
X187.75Y-49.0
X187.75Y-142.0
M30
