M48
; DRILL file {KiCad 9.0.6} date 2025-12-23T22:26:12+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-23T22:26:12+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.450
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C5.500
%
G90
G05
T1
X60.592Y-125.075
X64.992Y-125.075
T2
X46.75Y-70.37
T3
X30.75Y-78.88
X46.75Y-134.12
T4
X24.75Y-23.5
X24.75Y-155.25
X198.5Y-23.5
X198.5Y-155.25
M30
