M48
; DRILL file {KiCad 9.0.6} date 2026-01-23T11:35:03+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-23T11:35:03+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.450
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C5.500
%
G90
G05
T1
X66.05Y-149.75
X70.45Y-149.75
T2
X52.0Y-66.57
T3
X36.0Y-75.08
X52.0Y-130.32
T4
X34.675Y-23.4
X34.675Y-153.55
X135.075Y-23.425
X135.15Y-153.55
M30
